# Generated by Django 4.0.5 on 2022-07-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronic',
            name='image_url',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
