# Generated by Django 4.0.5 on 2022-07-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_electronic_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronic',
            name='image_url',
            field=models.CharField(max_length=1000),
        ),
    ]
